finetune:
  lora: true
  bnb: false

lora_config:
  r: 256
  lora_alpha: 512
  lora_dropout: 0.01
  bias: "none"
  task_type: CAUSAL_LM

bnb_config:
  load_in_4bit: true
  bnb_4bit_quant_type: nf4
  bnb_4bit_compute_dtype: float32
  bnb_4bit_use_double_quant: true

training_arguments:
  output_dir: /hpc2hdd/home/yli106/smiles2mol/results_llama3
  overwrite_output_dir: true
  num_train_epochs: 10
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 64
  optim: adamw_torch
  evaluation_strategy: epoch
  save_steps: 200
  logging_steps: 100
  eval_steps: 1
  learning_rate: 1e-5
  weight_decay: 0.001
  fp16: false
  bf16: true
  max_grad_norm: 0.3
  max_steps: -1
  warmup_ratio: 0.01
  group_by_length: true
  lr_scheduler_type: linear

data:
  base_path: /hpc2hdd/home/yli106/smiles2mol/GEOM
  dataset: qm9
  train_set: train_data_40k.csv
  val_set: val_data_5k.csv
  test_set: test_data_200.pkl

model:
  base_path: /hpc2hdd/home/yli106/smiles_3d
  type: mistral
  size: 7b
  save_path: /hpc2hdd/home/yli106/smiles2mol/models/finetuned
  peft_path: /hpc2hdd/home/yli106/smiles2mol/results_mistral/checkpoint-9400

inference:
  max_length: 4000
  max_new_tokens: 100
  multiplier: 2
  do_sample: true
  top_k: 10
  top_p: 0.9
  temperature: 0.7
  save_path: /hpc2hdd/home/yli106/smiles2mol/GEOM/generated